#Large membrane interacting with nanoplastics
#DPD simulation for DOPC membrane (four-to-one mapping) 5-beads tail
units		lj
atom_style	molecular
boundary	p p p

#Geometry (read in membrane with preinserted nanoplastics)
variable	rseed equal 2
read_data	DOPCt5_largemembrane_wtetra_size5.6_vel-5_embedded_run${rseed}.config	
lattice		fcc 3.0
region		box block EDGE EDGE EDGE EDGE EDGE EDGE units box
region		water block EDGE EDGE EDGE EDGE EDGE EDGE units box

#Group definition
variable        dpdseed equal 910+v_rseed

group		DOPC type 1 2 3 4 5
group		head type 1 2
group		tail type 4 5
group		glycerol type 3
group		Q0 type 1
group		Qa type 2
group		Na type 3
group		C type 4 5
group		W type 6
group		tetra type 7 8

group		nonrigid type 1 2 3 4 5 6
group		dump type 1 2 3 4 5 7 8

#Force field setup
mass		* 1.0
pair_style	dpd 1.0 1.0 ${dpdseed}
pair_coeff	* * 25 4.5 1.0

pair_coeff	1 1*2 25 4.5 1.0
pair_coeff	1 3 25 4.5 1.0
pair_coeff	1 4*5 100 4.5 1.0
pair_coeff	1 6 25 4.5 1.0
pair_coeff	1 7*8 100 4.5 1.0

pair_coeff	2 2 25 4.5 1.0
pair_coeff	2 3 25 4.5 1.0
pair_coeff	2 4*5 100 4.5 1.0
pair_coeff	2 6 25 4.5 1.0
pair_coeff	2 7*8 100 4.5 1.0

pair_coeff	3 3 25 4.5 1.0
pair_coeff	3 4*5 35 4.5 1.0
pair_coeff	3 6 25 4.5 1.0
pair_coeff	3 7*8 35 4.5 1.0

pair_coeff	4 4*5 25 4.5 1.0
pair_coeff	4 6 100 4.5 1.0
pair_coeff	4 7*8 25 4.5 1.0

pair_coeff	5 5 25 4.5 1.0
pair_coeff	5 6 100 4.5 1.0
pair_coeff	5 7*8 25 4.5 1.0

pair_coeff	6 6 25 4.5 1.0
pair_coeff	6 7*8 100 4.5 1.0

pair_coeff	7 7*8 25 4.5 1.0

pair_coeff	8 8 25 4.5 1.0

#Bond potential
bond_style	harmonic
bond_coeff	* 128 0.5

bond_coeff	1*5 128 0.5
special_bonds	lj 0.0 1.0 1.0

#Angle potential
angle_style	harmonic
angle_coeff	* 10 180

angle_coeff	1 10 120
angle_coeff	2 10 180
angle_coeff	3 10 180
angle_coeff	4 10 180
angle_coeff	5 18 120
angle_coeff	6 10 180

#Settings
comm_modify	cutoff 3.0 vel yes
neigh_modify	every 1 delay 0 check yes exclude molecule/intra tetra
timestep	0.01

#Diagnostics
compute		bonddist all bond/local dist
compute		maxbond all reduce max c_bonddist
compute		avebond all reduce ave c_bonddist

variable	tdens equal count(all)/vol
print		"The system density is now ${tdens}"

#Output
thermo_style	custom step temp epair ebond eangle press c_avebond c_maxbond
thermo_modify	flush yes norm no
thermo		100


#Production (NVT)
fix		1 nonrigid nve
fix		rigid tetra rigid/nve single force 1 on on on torque 1 on on on
fix		com1 DOPC momentum 1 linear 1 1 1
fix		com2 W momentum 1 linear 1 1 1

variable	tension equal lz*(c_thermo_press[3]-0.5*(c_thermo_press[1]+c_thermo_press[2]))
variable	apl equal lx*ly/4608*2

#Calculate msd of lipids and nanoplastics
compute		Lchunk DOPC chunk/atom molecule
compute		msdchunk all msd/chunk Lchunk
variable        Lmsdxy equal ave(c_msdchunk[1]+c_msdchunk[2])
fix             msdout all ave/time 100 1 100 v_Lmsdxy file msd.dat

#Define nanoparticle orientation
compute		uwcoord tetra property/atom xu yu zu
variable	px1 equal c_uwcoord[64513][1]-xcm(tetra,x)
variable	py1 equal c_uwcoord[64513][2]-xcm(tetra,y)
variable	pz1 equal c_uwcoord[64513][3]-xcm(tetra,z)
variable	index equal 64513+count(tetra)-2
variable	px2 equal c_uwcoord[${index}][1]-xcm(tetra,x)
variable	py2 equal c_uwcoord[${index}][2]-xcm(tetra,y)
variable	pz2 equal c_uwcoord[${index}][3]-xcm(tetra,z)
variable	px3 equal c_uwcoord[64538][1]-xcm(tetra,x)
variable	py3 equal c_uwcoord[64538][2]-xcm(tetra,y)
variable	pz3 equal c_uwcoord[64538][3]-xcm(tetra,z)
variable	px4 equal c_uwcoord[64708][1]-xcm(tetra,x)
variable	py4 equal c_uwcoord[64708][2]-xcm(tetra,y)
variable	pz4 equal c_uwcoord[64708][3]-xcm(tetra,z)
fix		nporientcat all ave/time 100 1 100 v_px1 v_py1 v_pz1 v_px2 v_py2 v_pz2 v_px3 v_py3 v_pz3 v_px4 v_py4 v_pz4 file orient_cart.dat mode scalar

variable	npzrel equal f_rigid[1][3]-xcm(DOPC,z)
variable	npx equal f_rigid[1][1]
variable	npy equal f_rigid[1][2]
variable	npz equal f_rigid[1][3]
variable	npximg equal f_rigid[1][13]
variable	npyimg equal f_rigid[1][14]
fix		nppos all ave/time 100 1 100 v_npzrel v_npx v_npy v_npz v_npximg v_npyimg file pos.dat mode scalar

#Calculate coordination number
compute		coordnum tetra coord/atom cutoff 1.0 1*2 3 4*5 6 
compute		cnumH all reduce sum c_coordnum[1]
compute		cnumG all reduce sum c_coordnum[2]
compute		cnumT all reduce sum c_coordnum[3]
compute		cnumW all reduce sum c_coordnum[4]
compute		coordnum2 tail coord/atom cutoff 1.0 6
compute		cnumTW all reduce sum c_coordnum2
fix		cnum all ave/time 100 1 100 c_cnumH c_cnumG c_cnumT c_cnumW c_cnumTW file cnum.dat mode scalar

dump		1 dump custom 50000 mem.lammpstrj id type mol x y z
dump_modify	1 flush yes
thermo_style	custom step temp epair ebond eangle press c_avebond c_maxbond v_tension v_apl lx ly lz f_rigid[1][3] f_rigid[1][6]
thermo_modify	flush yes norm no
thermo		100

restart		10000 restart.1 restart.2
run		4000000
write_data	DOPCt5_largemembrane_wtetra_size5.6_embedded_run${rseed}_4Meqm.config nocoeff
